---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: operators
spec:
  interval: 30m
  timeout: 10m
  retryInterval: 1m
  dependsOn:
    - name: operators
  path: infrastructure-as-code/kubernetes/clusters/${CLUSTER_NAME}/config
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: operators
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
    # substituteFrom:
    #   - kind: ConfigMap
    #     name: cluster-settings
