---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: operators
spec:
  interval: 1m
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: config
    - name: operators
  path: infrastructure-as-code/kubernetes/clusters/${CLUSTER_NAME}/controllers
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: operators
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  patches:
    - target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
      patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          interval: 30m
          timeout: 5m
          retryInterval: 1m
          force: true
          prune: true
          wait: true
          sourceRef:
            kind: GitRepository
            name: operators
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
