---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./namespace.yaml
  - ./pvc-media.yaml
  - ./jellyfin
  - ./adguard
  - ./homarr
  - ./jellyseerr
  # - ./radarr
  - ./transmission
  - ./prowlarr
  # - ./jackett
