---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
