---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/external-dns/
