---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns-system
spec:
  releaseName: external-dns
  interval: 5m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: "1.15.2"
  targetNamespace: external-dns-system
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-credentials
            key: CF_API_KEY
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-credentials
            key: CF_API_EMAIL
