apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: operators
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:i4qa,iv:FH2Q+sxECkZQoKixHr9MCZPL8r4Fl1NS7EK4By9UPXo=,tag:rv1AtWAX8509RcxMpl9zpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tfu8jht2uv5pwp2lfzyp0hqkcfxgpdty6ayg4c3ze030uche6u8sk6r66k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVjRaa2tYbWVkZENhMVMz
            OG5vc1gxT1JtSjdQckJTZGs2RkFDR3g2SVNBClBzZUltenZRbmFVRm5yYklUamJu
            ZXhBYVZISFA2RmhJeHc5NmFyUWxwSncKLS0tIEFreWdkclNON1pBd2lad1BhSVor
            cjZFVXM3U215NC9CWnphallWRHVjc2sKF4dD59oo1OmiJt3we+IXo7TzQfPsGrmH
            g7KDMnv+0dg2h/CeFzMW2wHAAxYvikJeQu8/nQ9dAT00A5IuGs9LQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T12:58:19Z"
    mac: ENC[AES256_GCM,data:6BuEXQPjjglHjqr5pcMVyL9lssyCl686rDVDulAgJXmz1ydnGXv/hour2elFXyL4OATWKbHV7Vfb/lsiJKqxCZD+18oo2dqZNW1TG5n1nTADZA8c8bNcFQT4oL2Sv4+gKDwWY4asHb+we6wEz3iwJJcUahNovJogPRWL2d06lxE=,iv:GAzTO7x0kf+7j6x5wPXN057gWunb7HejdF44ACGGnIo=,tag:aSa/ByWRJg6reZMKz0COwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
