---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: operators
spec:
  path: ./infrastructure-as-code/infra/kubernetes/controllers/ingress-nginx/app
  dependsOn:
    - name: helm
  prune: true
  force: true
  wait: true
  interval: 30m
  timeout: 10m
  retryInterval: 1m
