---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: operators
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  prune: true
  force: true
  path: ./infrastructure-as-code/kubernetes/applications/media
  sourceRef:
    kind: GitRepository
    name: operators
