---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
