---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: operators
spec:
  path: ./infrastructure-as-code/infra/kubernetes/applications/jellyseerr/app
  postBuild:
    substitute:
      APP_NAME: jellyseerr
      APP_NAMESPACE: media
      PVC_CAPACITY: "1Gi"
  dependsOn:
    - name: helm
