---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: applications
spec:
  secretName: wildcard-cert
  issuerRef:
    name: cloudflare-dns01
    kind: ClusterIssuer
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
