---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: applications
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: downloads
