---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: download
