---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/downloads"
