---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./namespace.yaml
  - ./pvc-media.yaml
  - ./pvc-download.yaml
  - ./kuma.mesh.yaml
  - ./jellyfin
  - ./adguard
  - ./homarr
  - ./jellyseerr
  - ./radarr
  # - ./transmission
  - ./prowlarr
  # - ./jackett
configMapGenerator:
  - name: domain-config
    literals:
      - DOMAIN=jardin
vars:
  - name: DOMAIN
    objref:
      kind: ConfigMap
      name: domain-config
      apiVersion: v1
    fieldref:
      fieldpath: data.DOMAIN
