---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./namespace.yaml
  - ./media.pvc.yaml
  - ./media.pv.yaml
  - ./download.pvc.yaml
  - ./download.pv.yaml
  - ./kuma.mesh.yaml
  - ./jellyfin
  - ./adguard
  - ./homarr
  - ./jellyseerr
  - ./radarr
  # - ./transmission
  - ./prowlarr
  # - ./jackett
