---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./media.pvc.yaml
  - ./media.pv.yaml
  - ./downloads.pvc.yaml
  - ./downloads.pv.yaml
  # - ./kuma.mesh.yaml
  - ./adguard
  - ./byparr
  - ./flaresolverr
  - ./homarr
  # - ./jellyfin # BUG: until it's impossible to enable nvidia on kube
  - ./jellyseerr
  - ./prowlarr
  - ./radarr
  - ./transmission
  - ./cloudflared-tunnel
