---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: applications
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  volumeName: media
