---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3000Gi
