---
# yamllint disable rule:line-length
keys:
  - &key age17r5jkhtwepl0k27r5q6kdsfsyqyzxf25s5dzv4xc2awtea6c8cjs5clu6q
# yamllint enable rule:line-length
creation_rules:
  - path_regex: .*.sops.(ovpn|txt|conf|env|yaml)
    key_groups:
      - age:
          - *key
