# SPDX-License-Identifier: AGPL-3.0-or-later
[book]
authors = ["jdauliac"]
language = "en"
multilingual = false
src = "./docs"
title = "Jardin technical documentation"
description = "As code documentation, managed with mdBook, mermaid, and vale."

[preprocessor]
[preprocessor.index]
renderer = ["html"]

[preprocessor.links]
renderer = ["html"]

[preprocessor.footnote]
renderer = ["html"]

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.cmdrun]
command = "mdbook-cmdrun"

[preprocessor.emojicodes]

[preprocessor.toc]
marker = "[[_TOC_]]"

[output]

[output.html]
renderer = ["html"]
additional-js = [
  "docs/mermaid/mermaid.min.js",
  "docs/mermaid/mermaid-init.js"
]

[output.linkcheck]
renderer = ["html"]
follow-web-links = true
