version = 1

[pipeline]
default_backend = "Nix"
use_default = true

[cluster]
surname = "cluster"

[cluster.targets]
[cluster.targets.node1]
surname = "node1"
# role = "leader"
role = "follower"
ip = '127.0.0.1'

[cluster.targets.node2]
surname = "node1"
# role = "leader"
role = "follower"
ip = '127.0.0.1'
