version = 1

[[annotations]]
path = [
  "kube/*",
  "src/*",
  "nix/*",
  "tests/*",
  "**/.*",
  "*.yaml",
  "*.yml",
  "*.toml",
  "flake.nix",
  "*.nix",
  ".*",
  "*.xml",
  "*.json",
  "*.sh",
  "**/*.zone",
  "**/Corefile"
]
SPDX-FileCopyrightText = "2022 Conformism <conformism@nofreedisk.space>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
  "*.md",
  "*.txt",
  "*.gif",
  "*.tape",
  "tests/e2e/os/nixos/id_ed25519"
]
SPDX-FileCopyrightText = "2022 Conformism <conformism@nofreedisk.space>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "*.lock"
SPDX-FileCopyrightText = "2022 Conformism <conformism@nofreedisk.space>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "*."
SPDX-FileCopyrightText = "2022 Conformism <conformism@nofreedisk.space>"
SPDX-License-Identifier = "CC0-1.0"
