---
version: "3"
set: [errexit, pipefail, nounset]
shopt: [globstar]
dotenv: [".env.local", ".env"]
includes:
  lint:
    taskfile: taskfiles/Lint.yaml
    dir: .
  dev:
    taskfile: taskfiles/Dev.yaml
    dir: .
tasks:
  init:
    silent: true
    run: "once"
    desc: ✅  Setup project
    cmds:
      - |
        lefthook install
    sources:
      - ./lefthook.yml
      - ./flake.nix
  formatter:nix:
    silent: true
    run: "once"
    desc: 💄 Format nix files
    sources:
      - "**/*.nix"
    generates:
      - "**/*.nix"
    cmds:
      - nix fmt
  formatter:
    silent: true
    desc: 💄 Format jardin
    aliases:
      - fmt
    deps:
      - task: formatter:nix
  test:lefthook:
    silent: true
    cmds:
      - |
        lefthook -- run pre-commit pre-push
    sources:
      - "lefthook.yml"
  install:
    silent: true
    run: "once"
    cmds:
      - sudo nixos-rebuild --flake . switch
  default:
    silent: true
    run: "once"
    cmds:
      - task: init
      - |
        task -l
