---
version: "3"
set: [errexit, pipefail, nounset]
shopt: [globstar]
dotenv: [".env.local", ".env"]
includes:
  lint:
    taskfile: taskfiles/Lint.yaml
    dir: .
  docs:
    taskfile: docs/Taskfile.yaml
tasks:
  init:
    silent: true
    run: "once"
    desc: ✅  Setup project
    cmds:
      - |
        lefthook install
    sources:
      - ./lefthook.yml
      - ./flake.nix
  formatter:nix:
    silent: true
    run: "once"
    desc: 💄 Format nix files
    sources:
      - "**/*.nix"
    generates:
      - "**/*.nix"
    cmds:
      - nix fmt
  formatter:
    silent: true
    desc: 💄 Format jardin
    aliases:
      - fmt
    deps:
      - task: formatter:nix
  build:
    silent: true
    desc: Build jardin
    sources:
      - ./src/**/*.rs
      - ./Cargo.toml
      - ./Cargo.lock
    generates:
      - ./target/debug/jardin
    cmds:
      - |
        cargo build
  test:lefthook:
    silent: true
    cmds:
      - |
        lefthook -- run pre-commit pre-push
    sources:
      - "lefthook.yml"
  default:
    silent: true
    run: "once"
    cmds:
      - task: init
      - |
        task -l
