# SPDX-License-Identifier: AGPL-3.0-or-later

---

version: "3"

set: [errexit, pipefail, nounset]
shopt: [globstar]

dotenv: [".env.local", ".env"]

tasks:
  init:
    silent: true
    desc: Setup project
    cmds:
      - |
        nix run nixpkgs#lefthook install
    sources:
      - ./lefthook.yml
      - ./flake.nix
  formatter::rust:
    silent: true
    desc: 💄Format rust files
    sources:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
    cmds:
      - |
        nix run nixpkgs#cargo fix -- --allow-staged --allow-dirty --all-targets
      - |
        nix run nixpkgs#cargo fmt -- --all
      - |
        nix run nixpkgs#cargo clippy -- --fix --allow-dirty --allow-staged
      - |
        nix run nixpkgs#cargo-deny check
  formatter::nix:
    silent: true
    desc: 💄Format nix files
    sources:
      - "**/*.nix"
    generates:
      - "**/*.nix"
    cmds:
      - |
        nix fmt
  formatter:
    silent: true
    desc: 💄Format jardin
    aliases:
      - fmt
    deps:
      - task: formatter::rust
      - task: formatter::nix
  lint::typos:
    silent: true
    cmds:
      - |
        nix run nixpkgs#typos -- --write-changes .
  lint:
    silent: true
    desc: 💄Lint jardin
    deps:
      # - task: lint::rust::clippy
      - task: lint::typos
  build:
    silent: true
    desc: Build jardin
    sources:
      - ./src/**/*.rs
      - ./Cargo.toml
      - ./Cargo.lock
    generates:
      - ./target/debug/jardin
    cmds:
      - |
        nix run nixpkgs#cargo build
  test::lefthook:
    silent: true
    cmds:
      - |
        nix run nixpkgs#lefthook -- run pre-commit pre-push
    sources:
      - "lefthook.yml"
  test::rust:unit:
    silent: true
    cmds:
      - |
        nix run nixpkgs#cargo llvm-cov nextest
      - |
        nix run nixpkgs#cargo mutants
    sources:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  test::rust::audit:
    silent: true
    cmds:
      - |
        nix run nixpkgs#cargo audit
    sources:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  toolchain:
    silent: true
    # desc: Run all development toolchain
    cmds:
      - task: build
      - task: formatter
      - task: lint
      - task: test::rust
      - task: test::rust::audit
  dev:
    silent: true
    desc: Run development mode
    cmds:
      - |
        nix run nixpkgs#go-task toolchain -- --watch
  run:
    silent: true
    desc: Run jardin
    cmds:
      - |
        nix run
  default:
    silent: true
    cmds:
      - task: init
      - |
        task -l
