---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 3m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/base/
  sourceRef:
    kind: GitRepository
    name: jardin
