---
apiversion: kustomize.toolkit.fluxcd.io/v1
kind: kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 3m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/clusters/${CLUSTER_NAME}
  sourceRef:
    kind: GitRepository
    name: jardin
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
