---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 3m
  timeout: 15m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/controllers
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-config
  sourceRef:
    kind: GitRepository
    name: jardin
