---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flux2
  namespace: kube-system
spec:
  repo: https://fluxcd-community.github.io/helm-charts
  chart: flux2
  targetNamespace: flux-system
  createNamespace: true
  version: "2.15.0"
  bootstrap: true
  valuesContent: |-
    installCRDs: true
    extraObjects:
      - apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: jardin
          namespace: flux-system
          annotations:
            "helm.sh/hook": post-install,post-upgrade
        spec:
          interval: 1m
          ref:
            branch: main
          url: https://github.com/Dauliac/jardin.git
      - apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: base
          namespace: flux-system
          annotations:
            "helm.sh/hook": post-install,post-upgrade
        spec:
          interval: 1m
          timeout: 5m
          retryInterval: 1m
          prune: true
          wait: true
          path: ./kube/base/
          sourceRef:
            kind: GitRepository
            name: jardin
