---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: flux2
  namespace: kube-system
spec:
  repo: https://fluxcd-community.github.io/helm-charts
  chart: flux2
  targetNamespace: flux-system
  createNamespace: true
  version: "2.15.0"
  timeout: 20m
  valuesContent: |-
    installCRDs: true
