---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jardin
  namespace: flux-system
spec:
  interval: 2m
  ref:
    branch: main
  url: https://github.com/Dauliac/jardin.git
