---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  interval: 1m
  timeout: 20m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/base/
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-config
  sourceRef:
    kind: GitRepository
    name: jardin
