---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.2.1
  timeout: 60s
