---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  prune: true
  path: ./kube/base
  sourceRef:
    kind: GitRepository
    name: jardin
  decryption:
    provider: sops
    secretRef:
      name: sops-age
