---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  annotations:
    ignore-check.kube-linter.io/latest-tag: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/drop-net-raw-capability: >-
      FIXME: fix this one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn
          ports:
            - containerPort: 9091
          envFrom:
            - secretRef:
                name: transmission-vpn-credentials
          env:
            - name: OPENVPN_PROVIDER
              value: custom
            - name: OPENVPN_CONFIG
              value: udp
            - name: LOCAL_NETWORK
              value: 10.244.0.0/16 # TODO: define this with cluster variable
          volumeMounts:
            - name: openvpn-config-volume
              mountPath: udp.ovpn
              subPath: udp.ovpn
            # - name: config-volume # TODO: define transmission config here
            #   mountPath: /config
            - name: data-volume
              mountPath: /data
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: openvpn-config-volume
          secret:
            secretName: transmission-vpn-openvpn-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: download
