---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  annotations:
    ignore-check.kube-linter.io/latest-tag: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/drop-net-raw-capability: >-
      FIXME: fix this one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
        - name: init-openvpn-config
          image: alpine:latest # Image légère pour copier les fichiers
          command: ["/bin/sh", "-c"]
          args:
            - |-
              ls /tmp/ovpn/
              cp /tmp/ovpn/* /etc/openvpn/custom/
              echo "Done"
              ls /etc/openvpn/custom/
          volumeMounts:
            - name: openvpn-config-volume
              mountPath: /tmp/ovpn
              readOnly: true
            - name: openvpn-runtime-config
              mountPath: /etc/openvpn/custom
      containers:
        - name: transmission
          image: haugene/transmission-openvpn
          ports:
            - containerPort: 9091
          envFrom:
            - secretRef:
                name: transmission-vpn-credentials
            - configMapRef:
                name: transmission-config
          volumeMounts:
            - name: openvpn-runtime-config
              mountPath: /etc/openvpn/custom
            - name: data-volume
              mountPath: /data/downloads
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: openvpn-config-volume
          secret:
            secretName: transmission-vpn-openvpn-config
        - name: openvpn-runtime-config
          emptyDir: {} # Volume temporaire RW
        - name: data-volume
          persistentVolumeClaim:
            claimName: downloads
