---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml
  - ./config.yaml
  # - ./pvc-config.yaml
secretGenerator:
  - name: transmission-vpn-credentials
    envs:
      - ./credentials.sops.env
  - name: transmission-vpn-openvpn-config
    files:
      - ./udp.sops.ovpn
