---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-database
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: homarr-database
