---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./deployment.yaml
  - ./config-pvc.yaml
  - ./service.yaml
  - ./ingress.yaml
  # - ./pvc-config.yaml
