---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      version: "0.14.8"
      chart: metallb
  interval: 5m
  values:
    controller:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
    prometheus:
      serviceMonitor:
        enabled: true
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring
    speaker:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
