---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  interval: 1m
  driftDetection:
    mode: enabled
  chart:
    spec:
      # version: ""
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
