---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./deployment.yaml
  - ./dns-tcp.service.yaml
  - ./dns-udp.service.yaml
  - ./service-web.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: adguard-config
    files:
      - ./AdGuardHome.yaml
