---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: adguard
  resources:
    requests:
      storage: 1Gi
