---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: applications
spec:
  selector:
    app: adguard
  type: LoadBalancer
  externalTrafficPolicy: Local # Optionnel : Préserve l'IP source
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp
