---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: operators
spec:
  path: ./infrastructure-as-code/kubernetes/controllers/helm/repositories
  prune: true
  force: true
  wait: true
  interval: 30m
  timeout: 10m
  retryInterval: 1m
