---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: radarr
spec:
  scaleTargetRef:
    name: radarr
    kind: Deployment
    apiVersion: apps/v1
    service: radarr
    port: 7878
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 100
      window: 3m
