---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: nvidia-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: nvidia-system
      interval: 1h
  values:
    toolkit:
      env:
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
