---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: applications
  labels:
    app: prowlarr
  annotations:
    ignore-check.kube-linter.io/latest-tag: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:1.31.2.4975-ls108
          env:
            - name: PGID
              value: "2000"
            - name: PUID
              value: "2000"
            - name: TZ
              value: Europe/Zurich
            - name: DOCKER_MODS
              value: ghcr.io/themepark-dev/theme.park:prowlarr
            - name: TP_THEME
              value: catppuccin-frappe
            - name: TP_COMMUNITY_THEME
              value: "true"
          ports:
            - name: http
              containerPort: 9696
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            failureThreshold: 30
            timeoutSeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            failureThreshold: 2
            timeoutSeconds: 3
            periodSeconds: 30
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 250Mi
              cpu: 200m
          volumeMounts:
            - name: data
              mountPath: /config
            - name: backup
              mountPath: /config/Backups
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-data
        - name: backup
          persistentVolumeClaim:
            claimName: prowlarr-backup
