---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: applications
  annotations:
    ignore-check.kube-linter.io/latest-tag: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:1.21.2-nightly
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: ${CONFIG_TIMEZONE}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: static-config
              mountPath: /config/config.xml
              subPath: config.xml
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-pvc
        - name: static-config
          configMap:
            name: prowlarr-config
