---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./service.yaml
  - ./deployment.yaml
  - ./config.pvc.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: prowlarr-config
    files:
      - ./config.xml
