---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/config/prowlarr"
