---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: prowlarr
  resources:
    requests:
      storage: 100Mi
