---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: operators
spec:
  releaseName: kyverno
  targetNamespace: kyverno-system
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: operators
      version: 3.2.6
  interval: 1h
