---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-add-ons-http
  namespace: keda-system
spec:
  releaseName: keda-add-ons-http
  interval: 5m
  chart:
    spec:
      chart: keda-add-ons-http
      sourceRef:
        kind: HelmRepository
        name: keda
        # version: "2.9.4"
  targetNamespace: keda-system
  upgrade:
    remediation:
      remediateLastFailure: true
