apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: operators
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  prune: true
  force: true
  path: ./infrastructure-as-code/infra/kubernetes/controllers/flux/cluster
  sourceRef:
    kind: GitRepository
    name: operators
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
