---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  path: ./deploy/controllers/flux-installation
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      CLUSTER_NAME: ${CLUSTER_NAME}
