---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: operators
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: operators
      version: 4.9.0
  interval: 1h
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: "ingress-nginx"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 1000m
        memory: 1Gi
        ephemeral-storage: 100Mi
    controller:
      service:
        externalTrafficPolicy: "Local"
      config:
        proxy-buffer-size: "32k"
        proxy-buffers-number: "8"
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
