---
version: "3"
tasks:
  default:
    desc: ⚡ Run e2e nixOs tests vm for development
    silent: true
    run: "once"
    deps:
      - build
    cmds:
      - "nix build \\\n  '.#devInfraNixOs' \n./result/bin/start\n"
  ssh:
    desc: 🐚 Get shell
    deps:
      - build
    cmds:
      - ./result/bin/ssh
  build:
    internal: true
    cmds:
      - nix build '.#devInfraNixOs'
