---
# NOTE: Official doc : https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tunnel
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tunnel
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:1710-3f6b1f24d036
          imagePullPolicy: Always
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
            - --token $TOKEN
          ports:
            - containerPort: 2000
          envFrom:
            - secretRef:
                name: cloudflared-tunnel-credentials
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: cloudflared-tunnel-credentials
        - name: config
          configMap:
            name: cloudflared-tunnel-config
            items:
              - key: config.yaml
                path: config.yaml
