---
tunnel: f41a79e5-7adc-425a-84ab-64e471b2de7a
# credentials-file: /etc/cloudflared/creds/tunnel.json
metrics: 0.0.0.0:2000
no-autoupdate: true
originRequest:
  keepAliveTimeout: 30s
ingress:
  - hostname: streaming.${DOMAIN}
    service: https://jellyfin.${DOMAIN}
  - hostname: go.${DOMAIN}
    service: https://jellyseer.${DOMAIN}
  - hostname: ssh.${DOMAIN}
    service: ssh://${IP_ADDRESS}
  - service: http_status:404
