---
tunnel: f41a79e5-7adc-425a-84ab-64e471b2de7a
# credentials-file: /etc/cloudflared/creds/tunnel.json
metrics: 0.0.0.0:2000
no-autoupdate: true
originRequest:
  keepAliveTimeout: 30s
ingress:
  - hostname: sun.${DOMAIN}
    service: http://${IP_ADDRESS}:8096
  - hostname: go.${DOMAIN}
    service: http://jellyseerr.applications.svc.cluster.local:5055
  - hostname: radarr.${DOMAIN}
    service: http://radarr.applications.svc.cluster.local:5055
  - hostname: ssh.${DOMAIN}
    service: ssh://${IP_ADDRESS}:22
  - service: http_status:404
