---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./cloudflared-tunnel.deployment.yaml
configMapGenerator:
  - name: cloudflared-tunnel-config
    files:
      - ./config.yaml
secretGenerator:
  - name: cloudflared-tunnel-credentials
    envs:
      - ./token.sops.env
