---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux2-sync
  namespace: flux-system
spec:
  interval: 3m
  chart:
    spec:
      chart: flux2-sync
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
