---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: operators
spec:
  path: ./infrastructure-as-code/kubernetes/controllers/kyverno/app/
  dependsOn:
    - name: helm
