---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: operators
spec:
  releaseName: kyverno-policies
  targetNamespace: kyverno-system
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: operators
      version: 3.2.5
  interval: 1h
