---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx-system
      interval: 5m0s
  values:
    controller:
      allowSnippetAnnotations: true
      updateStrategy:
        type: Recreate
      ingressClass: nginx
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/nginx"
      service:
        loadBalancerIP: "${IP_ADDRESS}"
        annotations:
          metallb.universe.tf/allow-shared-ip: "public-ip-${IP_ADDRESS}"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
