---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress
      version: "0.18.0"
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: kong-system
  values:
    # controller:
    #   ingressController:
    #     image:
    #       repository: kong/kubernetes-ingress-controller
    #       tag: "3.4.3"
    gateway:
      env:
        router_flavor: expressions
    proxy:
      type: LoadBalancer
      externalIPs:
        - 192.168.1.100
