version = 1

[pipeline]
backend = "nix"

[pipeline.jobs.bootstrap]
statefull = true

[pipeline.jobs.dns]
depends = []

[pipeline.jobs.provisioning]
depends = ["bootstrap"]

[pipeline.jobs.applications]
# with kube or docker or 
statefull = true
depends = ["provisioning"]

[cluster]
surname = "cluster"
domain = "my.domain"

[cluster.targets]
[cluster.targets.node1]
surname = "node1"
name_server = "node2"
role = "leader"
ip = '127.0.0.1'

[cluster.targets.node2]
surname = "node1"
role = "follower"
ip = "127.0.0.1"
