---
apiVersion: charts.konghq.com/v1alpha1
kind: Kong
metadata:
  name: kong
  namespace: operators
spec:
  resources:
    limits:
      cpu: 500m
      memory: 2G
    requests:
      cpu: 100m
      memory: 512Mi
  ingressController:
    enabled: true
    ingressClass: kong-ingress-class
    installCRDs: false
  cluster:
    enabled: true
    tls:
      enabled: true
      servicePort: 8005
      containerPort: 8005
  clustertelemetry:
    enabled: true
    tls:
      enabled: true
      servicePort: 8006
      containerPort: 8006
  proxy:
    enabled: false
  admin:
    enabled: true
    labels:
      enable-metrics: "true"
    type: NodePort
    http:
      enabled: true
      nodePort: 30001
    tls:
      enabled: false
    ingress:
      enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  enterprise:
    enabled: true
    rbac:
      enabled: false
    smtp:
      enabled: false
    license_secret: kong-enterprise-license
    portal:
      enabled: true
    ingress:
      enabled: true
  manager:
    enabled: true
    type: NodePort
    http:
      nodePort: 30002
    tls:
      enabled: false
    ingress:
      enabled: true
  secretVolumes:
    - kong-cluster-cert
  postgresql:
    enabled: true
    postgresqlUsername: kong
    postgresqlDatabase: kong
    postgresqlPassword: kong
  portal:
    enabled: true
    type: NodePort
    http:
      enabled: true
      nodePort: 30003
    ingress:
      enabled: true
  portalapi:
    enabled: true
    http:
      enabled: true
      nodePort: 30004
    tls:
      enabled: false
    type: NodePort
    ingress:
      enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
  status:
    enabled: true
    type: ClusterIP
