---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kong
  namespace: operators
spec:
  channel: alpha.1
  name: kong
  source: operatorhubio-catalog
  sourceNamespace: olm
