---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homarr
  name: homarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
