---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "Europe/Paris"
            - name: PORT
              value: "5055"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config
