---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda-system
spec:
  releaseName: keda
  interval: 5m
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
      # version: "2.9.4"
  targetNamespace: keda-system
  upgrade:
    remediation:
      remediateLastFailure: true
