---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jardin-tests
  namespace: operators
spec:
  interval: 10m
  timeout: 2m
  retryInterval: 1m
  prune: true
  force: true
  path: "./infrastructure-as-code/kubernetes/controllers/flux"
  sourceRef:
    kind: GitRepository
    name: operators
  postBuild:
    substitute:
      CLUSTER_NAME: jardin-tests
      DOMAIN: localhost
