---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: operators
spec:
  releaseName: pihole
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: operators
      version: 2.26.0
  interval: 1h
  values:
    dnsmasq:
      # customDnsEntries:
      #   - address=/nas/192.168.178.10
      # customCnameEntries:
      #   - cname=foo.nas,nas
    persistentVolumeClaim:
      enabled: true
    serviceWeb:
      loadBalancerIP: 192.168.178.252
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: pihole-svc
      # type: LoadBalancer
    serviceDns:
      loadBalancerIP: ${LOADBALANCER_IP}
      # annotations:
      #   metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
