---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: operators
spec:
  releaseName: pihole
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: savepointsam
        namespace: operators
      version: 0.2.0
  interval: 1h
  values:
    pihole:
      timezone: Europe/Paris
      upstream:
        - 9.9.9.9
        - 1.1.1.1
      webui:
        admin:
          # TODO: use sops secrets to manage configs
          email: fake@pihole.com
          password: "!@bhex!!@sss/.2@@Asb1@97"
    persistence:
      enabled: true
      existingClaim: "pihole-config"
