---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: operators
spec:
  releaseName: pihole
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: operators
      version: 2.26.0
  interval: 1h
  values:
    # dnsmasq:
      # customDnsEntries:
      #   - address=/nas/192.168.178.10
      # customCnameEntries:
      #   - cname=foo.nas,nas
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole
    ingress:
      enabled: true

    DNS1: 9.9.9.9
    DNS2: 1.1.1.1
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 9.9.9.9
    serviceWeb:
      type: ClusterIP
    serviceDns:
      enabled: true
      nodePort: "30950"
    serviceDhcp:
      enabled: true
      nodePort: "30951"
