---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  labels:
    app: private-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-dns
  template:
    metadata:
      labels:
        app: private-dns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
            cpu: 100m
          requests:
            memory: 70Mi
            cpu: 10m
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        - containerPort: 9153
          protocol: TCP
      volumes:
      - name: config-volume
        configMap:
          name: coredns
