---
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  selector:
    app: coredns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
  type: ClusterIP
  clusterIP: 10.96.255.250
