---
version: "3"
tasks:
  default:
    desc: ⚡ Run e2e nixOs tests vm for development
    silent: true
    run: "once"
    deps:
      - build
    cmds:
      - |
        nix build \
          '.#devInfraNixOs'
          ./result/bin/start
  ssh:
    desc: 🐚 Get shell
    deps:
      - build
    cmds:
      - ./result/bin/ssh
  build:
    internal: true
    cmds:
      - nix build '.#devInfraNixOs'
  debug:
    silent: true
    run: "once"
    desc: Run jardin in debug mode
    deps:
      - task: build
    cmds:
      - |
        ./target/debug/jardin -c jardin.toml deploy
