---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-controller
  namespace: flux-system
spec:
  interval: 3m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/controllers/ingress-nginx
  dependsOn:
    - name: monitoring-controller
    - name: metallb-controller
    - name: loadbalancer-controller
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-config
  sourceRef:
    kind: GitRepository
    name: jardin
