---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda-http-controller
  namespace: flux-system
spec:
  interval: 3m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/controllers/keda-http
  dependsOn:
    - name: keda-controller
  sourceRef:
    kind: GitRepository
    name: jardin
