---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./kuma
  - ./local-path-provisioner
  - ./monitoring.kustomization.yaml
  - ./metallb.kustomization.yaml
  - ./loadbalancer.kustomization.yaml
  - ./ingress-nginx.kustomization.yaml
  - ./external-dns.kustomization.yaml
