---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./kuma
  # - ./nvidia # BUG: impossible to install nvidia driver operator
  - ./cert-manager.kustomization.yaml
  - ./cluster-issuer.kustomization.yaml
  - ./external-dns.kustomization.yaml
  - ./ingress-nginx.kustomization.yaml
  - ./keda-http.kustomization.yaml
  - ./keda.kustomization.yaml
  - ./loadbalancer.kustomization.yaml
  - ./local-path-provisioner
  - ./metallb.kustomization.yaml
  - ./monitoring.kustomization.yaml
