---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loadbalancer-controller
  namespace: flux-system
spec:
  interval: 3m
  timeout: 5m
  retryInterval: 1m
  prune: true
  wait: true
  path: ./kube/controllers/loadbalancer
  dependsOn:
    - name: metallb-controller
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-config
  sourceRef:
    kind: GitRepository
    name: jardin
