---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-dns01
spec:
  acme:
    email: "${LETS_ENCRYPT_EMAIL}"
    server: "${LETS_ENCRYPT_SERVER}"
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
      - dns01:
          cloudflare:
            email: "${LETS_ENCRYPT_EMAIL}"
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api-token
              key: api-key
