---
namespace: cert-manager
resources:
  - ./cluster-issuer.yaml
secretGenerator:
  - name: cert-manager-cloudflare-api-token
    files:
      - api-token=./api-key.sops.txt
configurations:
  - ./namereference.yaml
