---
namespace: cert-manager
resources:
  - ./cluster-issuer.yaml
secretGenerator:
  - name: cert-manager-cloudflare-api-token
    envs:
      - ./api-key.sops.env
configurations:
  - ./namereference.yaml
