---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-auth-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
