---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: operators
spec:
  releaseName: jellyfin
  targetNamespace: applications
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: operators
      version: 2.0.0
  interval: 1h
  values:
    ingress:
      enabled: true
      hosts:
        - host: jellyfin.${DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      # config:
      #   enabled: true
      #   existingClaim: "jellyfin-config"
      data:
        enabled: true
        existingClaim: "media"
        size: 200Gi
