---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./data-pvc.yaml
  - ./auth-db-pvc.yaml
  - ./token-secret.sops.yaml
  - ./admin-secret.sops.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: jellyfin-config-networks
    files:
      - ./configs/networks.xml
  - name: jellyfin-config-system
    files:
      - ./configs/system.xml
  - name: jellyfin-config-options
    files:
      - ./configs/options.xml
  - name: jellyfin-config-encoding
    files:
      - ./configs/encoding.xml
  - name: jellyfin-init-script
    files:
      - init-db.sh
