---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
