---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-jellyfin
  annotations:
    ignore-check.kube-linter.io/latest-tag: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/run-as-non-root: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-memory-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/unset-cpu-requirements: >-
      FIXME: fix this one
    ignore-check.kube-linter.io/drop-net-raw-capability: >-
      FIXME: fix this one
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: configure-jellyfin
          image: docker.io/linuxserver/jellyfin:10.7.7
          command: ["/usr/bin/env", "bash", "/configure.sh"]
          # command: ["/usr/bin/env", "bash", "-c", "sleep infinity"]
          envFrom:
            - secretRef:
                name: jellyfin-admin-secrets
          volumeMounts:
            - name: script
              mountPath: /configure.sh
              subPath: configure.sh
            - name: config
              mountPath: /etc/configure-jellyfin/movies.json
              subPath: movies.json
            - name: config
              mountPath: /etc/configure-jellyfin/tv_show.json
              subPath: tv_shows.json
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: configure-jellyfin-config
        - name: script
          configMap:
            name: configure-jellyfin-script
