---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ./config-pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./job.yaml
configMapGenerator:
  - name: configure-jellyfin-config
    files:
      - movies.json=./movies.json
      - tv_shows.json=./tv_shows.json
  - name: configure-jellyfin-script
    files:
      - ./configure.sh
secretGenerator:
  - name: jellyfin-admin-secrets
    envs:
      - ./admin.sops.env
