---
version: "3"
set: [errexit, pipefail, nounset]
shopt: [globstar]
tasks:
  default:
    desc: 📚 Build the documentation
    run: once
    cmds:
      - task: lint
      - task: build
  build:
    silent: true
    internal: true
    run: once
    deps:
      - build:changelog
      - build:vhs
    cmds:
      - mdbook build
  lint:
    silent: true
    internal: true
    run: once
    deps:
      - lint:vale
      - lint:markdownlint
  lint:markdownlint:
    silent: true
    internal: true
    run: once
    sources:
      - "./**/*.md"
      - README.md
    cmds:
      - |
        markdownlint-cli2 --fix \
          "./**/*.md" \
          "../README.md" \
          "#./CHANGELOG.md" \
          "#./SUMMARY.md" \
          "#./styles" \
  lint:vale:
    silent: true
    internal: true
    run: once
    sources:
      - "./**/*"
      - README.md
    vars:
      MULTILINES_FILES:
        sh: |
          fd \
            --exclude="styles" \
            --exclude="SUMMARY.md" \
            --exclude="CHANGELOG.md" \
            --exclude="target" md .
      FILES: '{{.MULTILINES_FILES | replace "\n" " "}}'
    cmds:
      - vale {{.FILES}} ../README.md
  lint:mdformat:
    silent: true
    internal: true
    run: once
    sources:
      - "./**/*.md"
      - README.md
    cmds:
      - mdformat .
  build:changelog:
    silent: true
    internal: true
    run: "once"
    desc: Generate changelog
    cmds:
      - convco changelog > CHANGELOG.md
  build:vhs:
    silent: true
    internal: true
    run: once
    sources:
      - ./vhs/**/*.tape
    cmds:
      - vhs ./vhs/getting-started.tape
