---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: applications
  labels:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {? {$component: ''} : ''}
  replicas: {? {.Values.cloudflared.replicas: ''} : ''}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {? {$component: ''} : ''}
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: cloudflared
          image: {? {$image: ''} : ''}
          imagePullPolicy: Always
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
            memory: 256Mi
          ports:
            - containerPort: 2000
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-tunnel
        - name: config
          configMap:
            name: cloudflared-tunnel
            items:
              - key: config.yaml
                path: config.yaml
