---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel
  namespace: applications
  labels:
    app.kubernetes.io/instance: cloudflared-tunnel
    app.kubernetes.io/component: reverse-proxy
data:
  config.yaml: |
    tunnel: {{ .Values.cloudflared.tunnelName }}
    credentials-file: /etc/cloudflared/creds/tunnel.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    originRequest:
      keepAliveTimeout: 30s
    ingress:
      - hostname: jellyfin
        service: https://jellyfin
      - service: http_status:404
