---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: applications
spec:
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: transmission
