---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: operators
spec:
  path: ./infrastructure-as-code/kubernetes/applications/transmission/app
  dependsOn:
    - name: helm
