---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: applications
spec:
  accessModes:
    - ReadWriteOnce
    requests:
      storage: 1Gi
  volumeName: jellyseerr-config
